# Generated by Django 5.2.12 on 2026-03-08 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_alter_timeentry_project_alter_timeentry_task_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='manual_duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
