# Generated by Django 5.2.12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def delete_all_time_entries(apps, schema_editor):
    """Remove all TimeEntry rows. TimerAction table is append-only and not touched."""
    TimeEntry = apps.get_model("tracking", "TimeEntry")
    TimeEntry.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("project_management", "0001_initial"),
        ("tracking", "0003_add_manual_duration_seconds"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action", models.CharField(choices=[("start", "Start"), ("stop", "Stop")], max_length=10)),
                ("occurred_at", models.DateTimeField()),
                (
                    "task_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timer_actions",
                        to="project_management.tasktype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timer_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "time_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timer_actions",
                        to="tracking.timeentry",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timer_actions",
                        to="project_management.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timer action",
                "verbose_name_plural": "Timer actions",
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.RunPython(delete_all_time_entries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="timeentry",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_entries",
                to="project_management.project",
            ),
        ),
        migrations.AlterField(
            model_name="timeentry",
            name="task_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="time_entries",
                to="project_management.tasktype",
            ),
        ),
    ]
