# Generated by Django 5.2.12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0004_timer_action_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeraction",
            name="value",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeraction",
            name="action",
            field=models.CharField(
                choices=[
                    ("start", "Start"),
                    ("stop", "Stop"),
                    ("manual", "Manual"),
                ],
                max_length=10,
            ),
        ),
    ]
